#!/usr/bin/env bash
#
# Fork off some amount of the UTxO owned by given signing key and mark the rest
# as fuel to be used by the hydra-node.
set -evx

function usage() {
    echo "Usage: $0 <cardano signing key file> <amount in lovelace>" >&2
    echo point to the cardano node socket >&2
    echo export  CARDANO_NODE_SOCKET_PATH="<path>/node.socket" >&2
    exit 1
}

[ ${#} -eq 2 ] || (echo "Wrong number of arguments" && usage)

sk=${1}
[ -f ${sk} ] || (echo "Not a file: ${sk}" && usage)

amount=${2}
[ -n "${amount}" ] || (echo "Missing argument: amount of lovelace" && usage)

# Invoke cardano-cli in running cardano-node container or via provided cardano-cli
function ccli() {
  docker run --rm -it \
    -v $PWD/mainnet_cardano_var:/mainnet_cardano_var       \
    -v $PWD/cardano-configurations:/cardano-configurations \
    -v $PWD/hydra-configuration:/hydra-configuration       \
    -v $PWD/local_peers:/local_peers                       \
    -v $PWD/local_secrets:/local_secrets                   \
    -v $PWD/work_dir:/work_dir                                       \
    -e CARDANO_NODE_SOCKET_PATH=mainnet_cardano_var/node.socket \
    inputoutput/cardano-node cli "$@"
}

vk=${sk%.sk}.vk
if [[ ! -f "${vk}" ]]; then
  ccli key verification-key --signing-key-file ${sk} --verification-key-file ${vk}
fi

addr=$(ccli address build --payment-verification-key-file $vk --mainnet)

utxo=$(ccli query utxo \
    --cardano-mode --epoch-slots 21600 \
    --mainnet \
    --address ${addr} \
    --out-file /dev/stdout)
totalLovelace=$(echo ${utxo} | jq -r 'reduce .[] as $item (0; . + $item.value.lovelace)')
countdown=30

echo "Waiting for funds to appear at address ${addr}"

while [[ ${totalLovelace} -eq 0 ]] && [[ ${countdown} -gt 0 ]]; do
  sleep 5
  utxo=$(ccli query utxo \
              --cardano-mode --epoch-slots 21600 \
	      --mainnet \
              --address ${addr} \
              --out-file /dev/stdout)
  totalLovelace=$(echo ${utxo} | jq -r 'reduce .[] as $item (0; . + $item.value.lovelace)')
  countdown=$((countdown - 1))
done

[[ ${countdown} -eq 0 ]] && echo "Error: insufficient funds" && exit 1

entries=$(echo ${utxo} | jq "to_entries|sort_by(.value.value.lovelace)|last")
input=$(echo ${entries} | jq '.key' | tr -d '"')
fuelAmount=$(echo ${entries} | jq ".value.value.lovelace - ${amount}")

mkdir -p work_dir
tx=$(mktemp -p work_dir)
ccli transaction build \
     --mainnet \
     --babbage-era \
     --cardano-mode --epoch-slots 21600 \
     --script-valid \
     --tx-in ${input} \
     --tx-out ${addr}+${fuelAmount} \
     --tx-out-datum-hash "a654fb60d21c1fed48db2c320aa6df9737ec0204c0ba53b9b94a09fb40e757f3" \
     --change-address ${addr} \
     --out-file ${tx}

ccli transaction sign \
     --mainnet \
     --tx-body-file ${tx} \
     --signing-key-file $sk \
     --out-file ${tx}.signed

ccli transaction submit \
    --cardano-mode \
    --epoch-slots 21600 \
    --mainnet \
    --tx-file ${tx}.signed
